// Code generated by MockGen. DO NOT EDIT.
// Source: snapshotsink.go

// Package mocksnapshotsink is a generated GoMock package.
package mocksnapshotsink

import (
	gomock "github.com/golang/mock/gomock"
)
