// Code generated by MockGen. DO NOT EDIT.
// Source: stable_store.go

// Package mockstablestore is a generated GoMock package.
package mockstablestore

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockStableStore is a mock of StableStore interface
type MockStableStore struct {
	ctrl     *gomock.Controller
	recorder *MockStableStoreMockRecorder
}

// MockStableStoreMockRecorder is the mock recorder for MockStableStore
type MockStableStoreMockRecorder struct {
	mock *MockStableStore
}

// NewMockStableStore creates a new mock instance
func NewMockStableStore(ctrl *gomock.Controller) *MockStableStore {
	mock := &MockStableStore{ctrl: ctrl}
	mock.recorder = &MockStableStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStableStore) EXPECT() *MockStableStoreMockRecorder {
	return m.recorder
}

// Set mocks base method
func (m *MockStableStore) Set(key, val []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", key, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set
func (mr *MockStableStoreMockRecorder) Set(key, val interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockStableStore)(nil).Set), key, val)
}

// Get mocks base method
func (m *MockStableStore) Get(key []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockStableStoreMockRecorder) Get(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStableStore)(nil).Get), key)
}

// SetUint64 mocks base method
func (m *MockStableStore) SetUint64(key []byte, val uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUint64", key, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUint64 indicates an expected call of SetUint64
func (mr *MockStableStoreMockRecorder) SetUint64(key, val interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUint64", reflect.TypeOf((*MockStableStore)(nil).SetUint64), key, val)
}

// GetUint64 mocks base method
func (m *MockStableStore) GetUint64(key []byte) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUint64", key)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUint64 indicates an expected call of GetUint64
func (mr *MockStableStoreMockRecorder) GetUint64(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUint64", reflect.TypeOf((*MockStableStore)(nil).GetUint64), key)
}
